# Generated by Django 2.2.6 on 2020-01-08 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields
import taggit.managers

class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_medium_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to='assets.Gallery'),
        ),
    ]
