# Generated by Django 3.1.4 on 2021-09-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_gallery_deletion'),
        ('production', '0010_meta_staff_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='diff_galleries',
            field=models.ManyToManyField(blank=True, related_name='prod_diffusion', to='assets.Gallery'),
        ),
    ]
