# Generated by Django 3.2.15 on 2022-10-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_gallery_deletion'),
        ('production', '0011_ordering_productionorganizationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='diff_galleries',
            field=models.ManyToManyField(blank=True, related_name='prod_diffusion', to='assets.Gallery'),
        ),
    ]
