# Generated by Django 3.2.15 on 2023-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_ordering_productionorganizationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtype',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
