# Generated by Django 4.1 on 2023-07-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_migratin_to_django4'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtype',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
