# Generated by Django 3.2.15 on 2023-05-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0005_migration_to_django2'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='continent',
            field=models.CharField(blank=True, choices=[('AS', 'Asia'), ('EU', 'Europe'), ('AF', 'Africa'), ('NA', 'North America'), ('SA', 'South America'), ('AU', 'Australia'), ('AN', 'Antartica')], max_length=2),
        ),
    ]
