# Generated by Django 3.2.15 on 2023-06-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0006_place_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='continent',
            field=models.CharField(blank=True, choices=[('AS', 'Asie'), ('EU', 'Europe'), ('AF', 'Afrique'), ('NA', 'Amérique du Nord'), ('SA', 'Amérique du Sud'), ('AU', 'Australie'), ('ME', 'Moyen Orient'), ('AN', 'Antarctique'), ('OC', 'Océanie')], max_length=2),
        ),
    ]
