# Generated by Django 4.1 on 2023-07-21 14:42

import diffusion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0013_event_subtype'),
        ('diffusion', '0007_alter_place_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='artist',
            field=models.ManyToManyField(blank=True, help_text='The awarded author - can be Artist or Staff', limit_choices_to=diffusion.models.staff_and_artist_user_limit, related_name='award', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='award',
            name='artwork',
            field=models.ManyToManyField(blank=True, help_text='The awarded artwork', related_name='award', to='production.artwork'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='event',
            field=models.ForeignKey(help_text='The event during which the award was given', limit_choices_to=diffusion.models.main_event_false, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='award', to='production.event'),
        ),
        migrations.AlterField(
            model_name='award',
            name='ex_aequo',
            field=models.BooleanField(default=False, help_text='Check in case of ex aequo'),
        ),
        migrations.AlterField(
            model_name='award',
            name='meta_award',
            field=models.ForeignKey(help_text='The meta award', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='award', to='diffusion.metaaward'),
        ),
        migrations.AlterField(
            model_name='metaaward',
            name='event',
            field=models.ForeignKey(help_text='The related event - must be a main event', limit_choices_to=diffusion.models.main_event_true, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_award', to='production.event'),
        ),
        migrations.AlterField(
            model_name='metaaward',
            name='label',
            field=models.CharField(help_text='The name of the award', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='metaaward',
            unique_together={('event', 'label')},
        ),
    ]
