# Generated by Django 3.1.13 on 2021-12-02 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_meta_staff_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0005_update_mothertongue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='FresnoyStaff',
        ),
    ]
