# Generated by Django 3.2.15 on 2022-11-02 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0012_add_diff_galleries_to_PROD'),
        ('people', '0006_languagesfield_newversion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='FresnoyStaff',
        ),
    ]
